### ISSUE TITLE
Empty value in path field type broken on 3.11 and below

### ISSUE THREAD

**Issue by JSCU-CNI** [fox-it/flow.record#131]
It seems that #122 introduced incompatible behaviour for cpython versions 3.11 and older. See the below `dissect.target` test failing on 3.11:

```
$ python --version
Python 3.11.9

$ pip freeze | grep flow\.record
flow.record==3.15
$ pytest tests/plugins/apps/browser/test_chrome.py
...
16 passed, 4 warnings in 2.55s

$ pip install flow.record==3.16.dev8
$ pytest tests/plugins/apps/browser/test_chrome.py
...
FAILED tests/plugins/apps/browser/test_chrome.py::test_chrome_windows_snapshots - 
AttributeError: 'windows_path' object has no attribute '_empty_path'

self = <[AttributeError("'windows_path' object has no attribute '_empty_path'") raised in repr()] windows_path object at 0x71d2597ec670>

    def __str__(self) -> str:
>       if self._empty_path:
E       AttributeError: 'windows_path' object has no attribute '_empty_path'

/usr/local/lib/python3.11/site-packages/flow/record/fieldtypes/__init__.py:701: AttributeError
```

**Comment by yunzheng** [comment]
@Miauwkeru I took the liberty to look into it, feel free to review the PR.

The cause is that on Python 3.11 and lower the `.parent` property of a Path object creates a new path by not using `super()` thus bypassing our own subclassed `__new__` in our own path field type.

The PR fixes it by defining it as a class variable, and also ensuring that `.parent` returns an empty path for empty paths.
